name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-version: ['stable', 'nightly']
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-version }}
      - name: Clone plenary.nvim
        run: git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
      - name: Run tests
        run: make test
